- name: Copy /var/log/audit/audit.log
  hosts: all
  tasks:
     - name: Copy file
       copy:
          src: /var/log/audit/audit.log
          dest: /var/log/selinux/test.audit.log
          owner: user
          group: user
          mode: 0644
