--- 
- 
  hosts: all
  name: "List all relevant Hardware & OS"
  tasks: 
    - 
      command: "lshw -short"
      name: "Execute the Uptime command over Command module"
      register: lshwoutput
    - 
      debug: 
        var: lshwoutput.stdout_lines
    - 
      command: "uname -a"
      name: "Uname command"
      register: unameout
    - 
      debug: unameout.stdout_lines
